const STATE = {
  CREATING_GAME: "CREATING_GAME",
  WAITING_FOR_HINT: "WAITING_FOR_HINT",
  DURING_HINT: "DURING_HINT",
  FINAL_GUESS: "FINAL_GUESS",
  SHOWING_RESULTS: "SHOWING_RESULTS"
}

export {
  STATE
}